apiVersion: v1
kind: Namespace
metadata:
  name: xfusion

---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: time-config
  namespace: xfusion
data:
   TIME_FREQ: "3"

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: xfusion
spec:
  containers:
  - image: busybox:latest
    name: time-check
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep $TIME_FREQ;done > /opt/data/time/time-check.log"]
    env:
    - name: time-config
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    volumeMounts:
    - name: log-volume
      mountPath: /opt/data/time/
  volumes:
  - name: log-volume
    emptyDir: {}
